events {}

http {
  # si tu upload des fichiers
  client_max_body_size 200m;

  # --- upstreams (noms = noms de tes services docker) ---
  upstream frontend { server restt-frontend:80; }
  upstream backend  { server restt-backend:8000; } 

  # --- HTTP -> HTTPS ---
  server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
  }

  # --- HTTPS ---
  server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/certs/restt.crt;
    ssl_certificate_key /etc/nginx/certs/restt.key;

    # headers utiles
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;

    # FRONT React
    location / {
      proxy_pass http://frontend;
    }
 
   # BACKEND DJANGO (appelé via /backend/ par le frontend Nginx-aware)
    location /backend/ {
      proxy_pass http://backend/api/;
    }

    # BACKEND DJANGO (appelé via /api/ si le frontend a été buildé avec REACT_APP_API_BASE_URL=/api/)
    location /api/ {
      proxy_pass http://backend/api/;
    }
  }
}