FROM nginx:alpine

# Copier la config nginx
COPY conf/nginx.conf /etc/nginx/nginx.conf

# Copier les certificats (optionnel si tu montes en volumes)
# COPY certs /etc/nginx/certs

# Expose ports
EXPOSE 80 443