# Generated by Django 4.2.4 on 2026-02-20 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restitutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restitutions_crees', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restitutions_modifiees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_nom', models.CharField(max_length=255, null=True)),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_selected', to='restitutions.restitutions')),
            ],
        ),
        migrations.CreateModel(
            name='Jointures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference1', models.JSONField()),
                ('reference2', models.JSONField()),
                ('type', models.CharField(choices=[('LJ', 'LEFT JOIN'), ('RJ', 'RIGHT JOIN'), ('IJ', 'INNER JOIN'), ('FJ', 'FULL JOIN')], max_length=10)),
                ('code_format1', models.IntegerField(null=True)),
                ('code_format2', models.IntegerField(null=True)),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jointures', to='restitutions.restitutions')),
            ],
        ),
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_structure', models.IntegerField()),
                ('name_structure', models.CharField(max_length=255, null=True)),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formats_selected', to='restitutions.restitutions')),
            ],
        ),
        migrations.CreateModel(
            name='Filtre_populations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur_logique', models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=50, null=True)),
                ('champs_cible', models.CharField(max_length=255)),
                ('operateur_comparaison', models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('==', '=='), ('!=', '!='), ('%', '%')], max_length=5)),
                ('parametre', models.JSONField()),
                ('id_precedente', models.IntegerField(blank=True, null=True)),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtres_pop', to='restitutions.restitutions')),
            ],
        ),
        migrations.CreateModel(
            name='Expressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.JSONField(null=True)),
                ('operateur_arithmetique', models.CharField(max_length=5, null=True)),
                ('id_precedente', models.IntegerField(blank=True, null=True)),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='restitutions.operations')),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_logique', models.CharField(choices=[('si', 'si'), ('sinon si', 'sinon si'), ('sinon', 'sinon')], max_length=8)),
                ('operateur_comparaison', models.CharField(blank=True, choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('==', '=='), ('!=', '≠'), ('%', '%')], max_length=5, null=True)),
                ('operateur_logique', models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=5, null=True)),
                ('id_precedente', models.IntegerField(blank=True, null=True)),
                ('champs_cible', models.ManyToManyField(blank=True, related_name='cible_conditions', to='restitutions.expressions')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='restitutions.operations')),
                ('valeur_reference', models.ManyToManyField(blank=True, related_name='valeur_conditions', to='restitutions.expressions')),
            ],
        ),
        migrations.CreateModel(
            name='Clause_regroupement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champs_cible', models.CharField(max_length=255, null=True)),
                ('id_precedente', models.IntegerField(blank=True, null=True)),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_regroupement', to='restitutions.expressions')),
            ],
        ),
        migrations.CreateModel(
            name='Champs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('as_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('taille', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('parametre', models.CharField(blank=True, max_length=100, null=True)),
                ('separateur', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('typeAttribut', models.CharField(blank=True, max_length=20, null=True)),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='champs', to='restitutions.restitutions')),
            ],
        ),
        migrations.CreateModel(
            name='Affichages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_affichage', models.CharField(max_length=255, null=True)),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affichages', to='restitutions.restitutions')),
            ],
        ),
    ]
