# Generated by Django 4.2.4 on 2026-03-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formats',
            name='status_llm',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='LLMModeles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_llm', models.CharField(max_length=255, null=True)),
                ('restitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llmmodeles', to='restitutions.restitutions')),
            ],
        ),
    ]
