# Generated by Django 4.2.4 on 2026-03-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0002_formats_status_llm_llmmodeles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formats',
            name='status_llm',
        ),
        migrations.AddField(
            model_name='restitutions',
            name='status_llm',
            field=models.BooleanField(default=True),
        ),
    ]
