# Generated by Django 4.2.4 on 2026-04-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0004_alter_filtre_populations_operateur_comparaison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=50, null=True),
        ),
    ]
