# Generated by Django 4.2.4 on 2026-04-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0006_llmmodeles_skill_alter_conditions_operateur_logique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('ET', 'ET'), ('OU', 'OU')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='llmmodeles',
            name='skill',
            field=models.CharField(default='auto', max_length=50),
        ),
    ]
