# Generated by Django 4.2.4 on 2026-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restitutions', '0007_alter_conditions_operateur_logique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodeles',
            name='documents_ref',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='filtre_populations',
            name='operateur_logique',
            field=models.CharField(choices=[('OU', 'OU'), ('ET', 'ET')], max_length=50, null=True),
        ),
    ]
